services:
  - type: web
    name: zeta2-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    rootDir: frontend

  - type: web
    name: zeta2-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    rootDir: backend
